name: github-profile-fetcher-e2e
run-name: E2E execute
on: [push]
defaults:
  run:
    shell: bash
    working-directory: jsprimer/e2e/github-profile-fetcher-e2e
jobs:
  run-e2e:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
    - name: Install Gauge
      run: curl -Ssl https://downloads.gauge.org/stable | sh
    - name: Setup Gauge
      run: gauge install java --version 0.9.1
    - name: Run E2E
      run: mvn clean test
