name: github-profile-fetcher-e2e
run-name: E2E execute
on: [push]
jobs:
  run-e2e:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
    - run: curl -Ssl https://downloads.gauge.org/stable | sh
    - run: gauge install java --version 0.9.1
    - run: mvn clean test
